/*
 * OCR helper functions using Tesseract.js.
 *
 * These helpers wrap the creation and management of a Tesseract worker. They
 * operate on canvas elements generated by pdf.js. Progress updates are
 * communicated via an optional callback.
 */

// Perform OCR on an array of canvases. Returns all recognized text concatenated.
// The progressCallback receives updates from Tesseract.js with information
// about the recognition progress. It should accept a single object with a
// `progress` property between 0 and 1.
export async function ocrCanvases(canvases, progressCallback = () => {}) {
  const worker = await Tesseract.createWorker({
    logger: progressCallback,
  });
  await worker.loadLanguage('eng');
  await worker.initialize('eng');
  let combinedText = '';
  for (const canvas of canvases) {
    const { data: { text } } = await worker.recognize(canvas);
    combinedText += text + '\n';
  }
  await worker.terminate();
  return combinedText;
}
